version: '3'

services:

  web-php:
    image: erighetto/drupal-dev
    container_name: "${PROJECT_NAME}_php"
    depends_on:
      - mailhog
    volumes:
      - "./docroot:${WEB_DOCUMENT_ROOT}"
    environment:
      WEB_DOCUMENT_ROOT: "${WEB_DOCUMENT_ROOT}"
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG}"
      POSTFIX_RELAYHOST: "${PROJECT_NAME}_mailhog:1025"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "443:443"
    volumes:
      - "./nginx/nginx-https-demo.localhost.pem:/etc/nginx/ssl/nginx-https-demo.localhost.crt"
      - "./nginx/nginx-https-demo.localhost-key.pem:/etc/nginx/ssl/nginx-https-demo.localhost.key"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - web-php
